name: Test Second Project with SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [testSDK1-completed]

jobs:
  fetch-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Java 11
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # 3. Create libs folder
    - name: Create libs folder
      run: mkdir -p libs

    - name: Find latest SDK JAR in JFrog
      id: find_jar
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      run: |
        LATEST_PATH=$(curl -s -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
        -X POST "$ARTIFACTORY_URL/artifactory/api/search/aql" \
        -d 'items.find({
            "repo": "sdk",
            "path": {"$match": "javaSDK/*/*"},
            "name": {"$match": "testSDK1-*.jar"}
          }).sort({"$desc": ["created"]}).limit(1)' | jq -r '.results[0] | "\(.repo)/\(.path)/\(.name)"')
        echo "LATEST_JAR_PATH=$LATEST_PATH" >> $GITHUB_ENV


    # 4. Download SDK JAR from JFrog
    - name: Download latest SDK JAR
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        LATEST_JAR_PATH: ${{ env.LATEST_JAR_PATH }}
      run: |
        mkdir -p libs
        curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
         -o libs/testSDK1-1.0.0.jar \
         $ARTIFACTORY_URL/$ARTIFACTORY_REPO/$LATEST_JAR_PATH

    - name: Debug JFrog Path
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_REPO: ${{ secrets.ARTIFACTORY_REPO }}
        LATEST_JAR_PATH: ${{ steps.find.outputs.latest_jar }}

      run: |
        echo "LATEST_JAR_PATH: $LATEST_JAR_PATH"

    # 5. Verify JAR is downloaded
    - name: List libs folder
      run: ls -l libs

    # 6. Build and run unit tests
    - name: Build and test
      run: ./gradlew clean test
